# Generated by Django 4.2.1 on 2023-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
